# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dimos"
#ZSH_THEME="avit"
#ZSH_THEME="agnoster"
#ZSH_THEME="xiong-chiamiov"
#ZSH_THEME="jonathan"
#ZSH_THEME="agnoster"
#ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git virtualenv)

source $ZSH/oh-my-zsh.sh

# User configuration

#export PATH="/home/dimos/bin:/home/dimos/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='vim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


export HISTSIZE=10000         # Increases size of history
export SAVEHIST=10000

#alias fansilent='echo level 1 | sudo tee /proc/acpi/ibm/fan'
#alias fanauto='echo level auto | sudo tee /proc/acpi/ibm/fan'
#alias fanfull='echo level disengaged | sudo tee /proc/acpi/ibm/fan'
#alias fanoff='echo level 0 | sudo tee /proc/acpi/ibm/fan'
#alias lighton='echo 255 | sudo tee /sys/class/leds/tpacpi\:\:thinklight/brightness'
#alias lightoff='echo 0 | sudo tee /sys/class/leds/tpacpi\:\:thinklight/brightness'
#alias turbooff='echo 1 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo'
#alias turboon='echo 0 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo'

alias oopen='xdg-open'

# Filesystem
alias ..='cd ..'            # Go up one directory
alias ...='cd ../..'        # Go up two directories
alias ....='cd ../../..'    # And for good measure
alias l='ls -lah'           # Long view, show hidden
alias la='ls -AF'           # Compact view, show hidden
alias ll='ls -lFh'          # Long view, no hidden

setopt NO_HUP
setopt NO_CHECK_JOBS

#--------------BASH INIT STAFF-----------------------------------

alias zshgit_on="git config --global --add oh-my-zsh.hide-status 0; git config --global --add oh-my-zsh.hide-dirty 0"
alias zshgit_off="git config --global --add oh-my-zsh.hide-status 1; git config --global --add oh-my-zsh.hide-dirty 1"

export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh
export GPG_AGENT_INFO=/run/user/$(id -u)/keyring/gpg:0:1
pgrep gnome-keyring || export $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

